[colors.primary]
background = "#132132"
foreground = "#fffeeb"
bright_foreground = "#fffeeb"

[colors.normal]
black = "#111e25"
red = "#ff6a6f"
green = "#a9dd9d"
yellow = "#fedf81"
blue = "#7098e6"
magenta = "#605779"
cyan = "#a8d2eb"
white = "#ffffff"

[colors.bright]
black = "#545f6e"
red = "#fd8489"
green = "#c9fd88"
yellow = "#f0eaaa"
blue = "#98b8e6"
magenta = "#e7d5ff"
cyan = "#a8d2eb"
white = "#ffffff"
