name: CI
on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: vim-airline/vim-airline
          path: ./vim-airline
      - uses: rhysd/action-setup-vim@v1
      - run: vim --not-a-term -N -E -c 'set t_Co=256 rtp+=.,./vim-airline | runtime plugin/airline.vim' -c 'try | colorscheme spring-night | AirlineTheme spring_night | catch | cquit | endtry' -c 'quit'
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - run: nvim -E -c 'set t_Co=256 termguicolors rtp+=.,./vim-airline | runtime plugin/airline.vim' -c 'try | colorscheme spring-night | AirlineTheme spring_night | catch | cquit | endtry' -c 'quit'
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gen
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: rustfmt
        run: cargo fmt -- --check --color always
      - name: clippy
        run: cargo clippy --color always -- -D warnings
